#~

server {
    http2 on;

    listen       443 ssl;
    listen       [::]:443 ssl;
    server_name  {{server_name}};

    # SSL
    ssl_certificate      {{cert_path}};
    ssl_certificate_key  {{key_path}};

    include      /etc/nginx/common/http-server.conf;

    # proxy
    location / {
        proxy_pass    {{proxy_path}};
    }
}
